name: Nature Bot Daily Post

on:
  schedule:
    - cron: "0 9,15,21 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Nature Bot
        run: python twitter_nature_bot.py
        env:
         X_API_KEY
         X_API_SECRET
         X_ACCESS_TOKEN
         X_ACCESS_SECRET

          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
